### ISSUE TITLE
"Attempt to get argmax of an empty sequence" error when Clustering dbscan

### ISSUE THREAD

**Issue by ojoaomorais** [erdogant/clusteval#3]
Hi, im having this error when using clusteval with cluster param "dbscan" with TFIDF, this is my code:

  `vectorizer = TfidfVectorizer(max_df=0.55,min_df=27)`
   `X = vectorizer.fit_transform(grams)`

   `svd = TruncatedSVD(int(X.shape[1] - 1))`
  ` normalizer = Normalizer(copy=False)`
   `lsa = make_pipeline(svd, normalizer)`
   `X = lsa.fit_transform(X)`

  `ce = clusteval(cluster='dbscan')`
  `ce.fit(X)`
  `ce.plot()`
 `ce.scatter(X)`
  `ce.dendrogram()`

This is the complete log error:

Traceback (most recent call last):
  File "/Volumes/HD 2/Repositorios/author_profiling_db_scan/main/__init__.py", line 82, in <module>
    ce.fit(X.toarray())
  File "/Volumes/HD 2/Repositorios/author_profiling_db_scan/venv/lib/python3.7/site-packages/clusteval/clusteval.py", line 153, in fit
    self.results = dbscan.fit(X, eps=None, epsres=50, min_samples=0.01, metric=self.metric, norm=True, n_jobs=-1, min_clust=self.min_clust, max_clust=self.max_clust, verbose=self.verbose)
  File "/Volumes/HD 2/Repositorios/author_profiling_db_scan/venv/lib/python3.7/site-packages/clusteval/dbscan.py", line 97, in fit
    idx = np.argmax(silscores)
  File "<__array_function__ internals>", line 6, in argmax
  File "/Volumes/HD 2/Repositorios/author_profiling_db_scan/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Volumes/HD 2/Repositorios/author_profiling_db_scan/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

**Comment by erdogant** [comment]
Can you print the head of X? Im not sure what the output of X = lsa.fit_transform(X) is.

**Comment by erdogant** [comment]
I see that you use svd for dim.reduction. But you do this by X.shape[1] - 1. Is this what you want? This may be causing the error.

Try using something like this:

`svd = TruncatedSVD(n_components=2)`

**Comment by erdogant** [comment]
@joaomoraiseu did the n_components fixed your issue?
